const mongoose = require('mongoose')

const productSchema = new mongoose.Schema({
    sellerID:{
        required:true,
        type:String,
    },
    productName:{
        required:true,
        type:String,
    },
    brand:{
        required:true,
        type:String,
    },
    category:{
        required:true,
        type:String,
    },
    mrp:{
        required:true,
        type:Number,
    },
    offerPrice:{
        required:true,
        type:Number,
    },
    size:{
        required:true,
        type:String,
    },
    stock:{
        required:true,
        type:Number,
    },
    description:{
        required:true,
        type:String,
    },
    specification:{
        required:true,
        type:String,
    },
    feature1:{
        required:true,
        type:String,
    },
    feature2:{
        required:true,
        type:String,
    },
    feature3:{
        required:true,
        type:String,
    },
    feature4:{
        required:true,
        type:String,
    },
    productColor:{
        required:true,
        type:String,
    },
    productMaterial:{
        required:true,
        type:String,
    },
    itemsInBox:{
        required:true,
        type:String,
    },
    warranty:{
        required:true,
        type:String,
    },
    weight:{
        required:true,
        type:String,
    },
})

module.exports = mongoose.model('Products', productSchema)